version: '2'

services:
  db:
      image: postgres
      environment:
           POSTGRES_DB: postgres
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
      volumes:
            - data-volume:/var/lib/postgresql/data
      ports:
            - "5433:5432"

  server:
      build: ./server
      volumes:
          - "./server:/server"
      ports:
          - "5000:5000"
      tty: true
      depends_on:
          - db
      
      command: bash -c "python3 server.py"
      restart: always

  web:
      build: ./web-app
      user: root      
      command: bash -c "cd miniAmazon && python3 manage.py makemigrations && python3 manage.py migrate && python3 ./Amazon/database.py && python3 manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - db
        - server
      restart: always
        
  nginx:
      image: nginx:latest
      ports:
          - "8000:8000"
      volumes:
          - ./web-app/nginx/config:/etc/nginx/conf.d
      depends_on:
          - web
        
volumes:
   data-volume: 